### ISSUE TITLE
I GET THIS ERROR WHILE CREATING A TELEGRAM BOT. SOMEONE PLEASE HELP ME 😭

### ISSUE THREAD

**Issue by ayushman979** [mkdryden/telegram-stats-bot#14] opened 2022-11-30 11:20 UTC
raceback (most recent call last):
  File "c:\Users\ayush\OneDrive\Desktop\tele\tele.py", line 2, in <module>
    from telegram.ext import *
  File "C:\Users\ayush\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\__init__.py", line 21, in <module>
    from .extbot import ExtBot
  File "C:\Users\ayush\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\ext\extbot.py", line 24, in <module>
    import telegram.bot
  File "C:\Users\ayush\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\bot.py", line 56, in <module>
    from telegram import (
ImportError: cannot import name 'Animation' from 'telegram' (C:\Users\ayush\AppData\Local\Programs\Python\Python311\Lib\site-packages\telegram\__init__.py)

**Comment by mkdryden** [comment] 2022-11-30 17:02
This is a duplicate of #9. Make sure you don't have the `python-telegram-bot` package installed, as per https://github.com/mkdryden/telegram-stats-bot/issues/9#issuecomment-1091828211

**Closed by mkdryden** 2022-11-30 17:02 UTC
Labels: duplicate
